[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs
MemoryWorkingSetLimit=1024

[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AddTorrentStopped=false
Session\AddTorrentToTopOfQueue=true
Session\BTProtocol=Both
Session\DefaultSavePath=/data/downloads/qbittorrent/completed
Session\ExcludedFileNames=
Session\GlobalMaxSeedingMinutes=5
Session\IgnoreLimitsOnLAN=true
Session\IgnoreSlowTorrentsForQueueing=true
Session\Interface=tun0
Session\InterfaceAddress=10.182.198.28
Session\InterfaceName=tun0
Session\MaxActiveDownloads=6
Session\MaxActiveTorrents=15
Session\MaxActiveUploads=3
Session\MaxConnections=-1
Session\MaxConnectionsPerTorrent=-1
Session\MaxUploads=-1
Session\MaxUploadsPerTorrent=-1
Session\Port=48463
Session\Preallocation=true
Session\QueueingSystemEnabled=true
Session\SSL\Port=54198
Session\ShareLimitAction=Stop
Session\SlowTorrentsDownloadRate=500
Session\SlowTorrentsInactivityTimer=10
Session\SlowTorrentsUploadRate=100
Session\TempPath=/data/downloads/qbittorrent/incomplete
Session\TempPathEnabled=true
Session\TorrentExportDirectory=/data/downloads/qbittorrent/torrents
Session\UseAlternativeGlobalSpeedLimit=false
Session\uTPRateLimited=false

[Core]
AutoDeleteAddedTorrentFile=IfAdded

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
PortForwardingEnabled=true
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
General\Locale=en
General\StatusbarExternalIPDisplayed=true
MailNotification\password=Chimperama123
MailNotification\req_auth=true
MailNotification\username=kylepitcock
WebUI\Address=*
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(TnSkzswnVdQCk/AQJenx4w==:hsaPzpqmZAix9DXKSm7T6QZxoyNgmR9A1er1b2dHj4HGvWSeS3XYSYnHLDI2J5SxhndwdkALyOJ0mcrXqPOUYw==)"
WebUI\ServerDomains=*
WebUI\Username=kylepitcock

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
